version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus/config:/etc/prometheus
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana-oss:8.4.5
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/secrets:/run/secrets
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin-password.txt
    ports:
      - 3000:3000
