version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.33.5
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/data/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
