global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [localhost:9090]
  - job_name: node-exporter
    dns_sd_configs:
      - names: [node-exporter]
        type: A
        port: 9100
