global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [localhost:9090]
  - job_name: node-exporter
    dns_sd_configs:
      - names: [node-exporter]
        type: A
        port: 9100
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: ^node_cpu_seconds_total|node_memory_(Buffers|Cached|MemFree|MemTotal)_bytes$
        action: keep
      - regex: instance
        action: labeldrop
